[0m17:37:59.515682 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021692879820>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021692761340>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021692761A00>]}


============================== 17:37:59.518681 | 322917e0-69aa-4241-bc16-8b8c3104131c ==============================
[0m17:37:59.518681 [info ] [MainThread]: Running with dbt=1.8.8
[0m17:37:59.519682 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\AliMurat Dinchdonmez\\.dbt', 'fail_fast': 'False', 'warn_error': 'None', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init dbt_snowflake_project', 'send_anonymous_usage_stats': 'True'}
[0m17:37:59.530685 [debug] [MainThread]: Starter project path: C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\include\starter_project
[0m17:37:59.540681 [info ] [MainThread]: 
Your new dbt project "dbt_snowflake_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m17:37:59.541685 [info ] [MainThread]: Setting up your profile.
[0m17:38:02.498546 [error] [MainThread]: Encountered an error:

[0m17:38:02.500546 [error] [MainThread]: Traceback (most recent call last):
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\cli\requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\cli\requires.py", line 101, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\cli\main.py", line 470, in init
    results = task.run()
              ^^^^^^^^^^
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 347, in run
    self.setup_profile(profile_name)
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 263, in setup_profile
    self.create_profile_from_target(adapter, profile_name=profile_name)
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 180, in create_profile_from_target
    self.create_profile_from_profile_template(profile_template, profile_name)
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 164, in create_profile_from_profile_template
    target = self.generate_target_from_input(prompts, initial_target)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\dbt\task\init.py", line 130, in generate_target_from_input
    target[key] = click.prompt(
                  ^^^^^^^^^^^^^
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\click\termui.py", line 164, in prompt
    value = prompt_func(prompt)
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AliMurat Dinchdonmez\OneDrive\Desktop\Concordia\342-Project\dbt-env\Lib\site-packages\click\termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m17:38:02.503546 [debug] [MainThread]: Command `dbt init` failed at 17:38:02.503546 after 3.05 seconds
[0m17:38:02.503546 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021696B534D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021697A90A40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002169719D5B0>]}
[0m17:38:02.503546 [debug] [MainThread]: Flushing usage events
